name: 'Deploy ASP.NET Core app to Azure Web App'

on:
  push:
    branches:
      - "master"


jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore Packages
        run: nuget restore DotNetAppSqlDb.sln
